# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  pod 'AFNetworking', '~> 2.1.0'
  pod 'ZSTest'
  # Pods for PodDemo

end
